spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/studs
    username: user
    password: password
    driverClassName: org.postgresql.Driver


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database: postgresql

lemsolaris:
  base_coordinates:
    x: 0
    y: 0
  max_anomaly_distance: 1000
